# Generated by Django 3.1.1 on 2020-09-29 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfiloUtente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sezione', models.BooleanField(default=False, verbose_name='Sezione')),
                ('is_centro_di_raccolta', models.BooleanField(default=False, verbose_name='Centro di raccolta')),
                ('is_donatore', models.BooleanField(default=False, verbose_name='Donatore')),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilo utente',
                'verbose_name_plural': 'Profili utenti',
            },
        ),
    ]
