# Generated by Django 3.1.1 on 2020-10-02 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donatori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255, unique=True)),
                ('ragione_sociale', models.CharField(blank=True, max_length=255)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('frazione', models.CharField(blank=True, max_length=255)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('citta', models.CharField(blank=True, max_length=255)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('presidente', models.CharField(blank=True, max_length=255)),
                ('segretario', models.CharField(blank=True, max_length=255)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sezione',
                'verbose_name_plural': 'Sezioni',
            },
        ),
    ]
