# Generated by Django 3.1.1 on 2020-10-10 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donatori', '0004_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_donazione', models.IntegerField(choices=[(1, 'Sangue intero'), (2, 'Plasma'), (3, 'Piastrine')], default=1)),
                ('data_donazione', models.DateField(default=datetime.date.today)),
                ('donatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donatori.donatore')),
            ],
            options={
                'verbose_name': 'Donazione',
                'verbose_name_plural': 'Donazioni',
                'unique_together': {('donatore', 'data_donazione')},
            },
        ),
    ]
