# Generated by Django 3.1.1 on 2020-10-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatori', '0006_auto_20201010_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donazione',
            name='tipo_donazione',
            field=models.IntegerField(choices=[(0, 'Non specificato'), (1, 'Sangue intero'), (2, 'Plasma'), (3, 'Piastrine')], default=0),
        ),
    ]
